repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    - id: clang-format
      args: [--Werror, --dry-run]
      types_or: [c++]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    - id: forbid-binary
    - id: markdownlint
    - id: git-check
